Fix Proplem.......... [rejected]
Fix Proplem.............

 λ git push -u origin main
info: please complete authentication in your browser...
To https://github.com/tahawe7/Tahawe-Files_Private.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/tahawe7/Tahawe-Files_Private.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details. 

Is.........................
This Video
youtube.com/watch?v=IeL7iq7Lb90